import { Injectable } from '@nestjs/common';
import { ConversationDto } from '../chat/dto/conversation.dto';

@Injectable()
export class ConversationsService {
  async getConversationsBoth(
    user_id: string,
    limit: number,
    offset: number,
  ): Promise<ConversationDto[]> {
    return Array.from(
      await Bun.sql`
        WITH conversation_users AS (
          SELECT CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          UNION SELECT RECEIVER_ID AS OTHER_USER_ID FROM SWIPES WHERE SWIPER_ID = ${user_id}
          UNION SELECT SWIPER_ID AS OTHER_USER_ID FROM SWIPES WHERE RECEIVER_ID = ${user_id}
        ),
        last_messages AS (
          SELECT DISTINCT ON (OTHER_USER_ID) OTHER_USER_ID, MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID FROM (
            SELECT MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID, RECEIVER_ID, CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          ) t ORDER BY OTHER_USER_ID, SENT_AT DESC
        )
        SELECT CU.OTHER_USER_ID, U.FULL_NAME, P.IMAGE_URL AS PROFILE_PICTURE_URL, 
               LM.MESSAGE_CONTENT AS LAST_MESSAGE, LM.MESSAGE_TYPE AS LAST_MESSAGE_TYPE, LM.SENDER_ID AS LAST_MESSAGE_SENDER_ID, 
               'both' AS swipe_category, 
               COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) AS LAST_MESSAGE_SENT_AT 
        FROM conversation_users CU 
        LEFT JOIN last_messages LM ON LM.OTHER_USER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S1 ON S1.SWIPER_ID = ${user_id} AND S1.RECEIVER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S2 ON S2.SWIPER_ID = CU.OTHER_USER_ID AND S2.RECEIVER_ID = ${user_id} 
        LEFT JOIN BLOCKS B1 ON B1.BLOCKER_ID = ${user_id} AND B1.BLOCKED_ID = CU.OTHER_USER_ID 
        LEFT JOIN BLOCKS B2 ON B2.BLOCKER_ID = CU.OTHER_USER_ID AND B2.BLOCKED_ID = ${user_id} 
        JOIN USERS U ON U.USER_ID = CU.OTHER_USER_ID 
        JOIN PHOTOS P ON P.UPLOADER_ID = CU.OTHER_USER_ID AND P.IS_PRIMARY = TRUE 
        WHERE B1.BLOCKED_ID IS NULL AND B2.BLOCKED_ID IS NULL 
          AND S1.SWIPE_TYPE = 'like' AND S2.SWIPE_TYPE = 'like'
        ORDER BY COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) DESC 
        OFFSET ${offset} LIMIT ${limit}
      `,
    );
  }

  async getConversationsYou(
    user_id: string,
    limit: number,
    offset: number,
  ): Promise<ConversationDto[]> {
    return Array.from(
      await Bun.sql`
        WITH conversation_users AS (
          SELECT CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          UNION SELECT RECEIVER_ID AS OTHER_USER_ID FROM SWIPES WHERE SWIPER_ID = ${user_id}
          UNION SELECT SWIPER_ID AS OTHER_USER_ID FROM SWIPES WHERE RECEIVER_ID = ${user_id}
        ),
        last_messages AS (
          SELECT DISTINCT ON (OTHER_USER_ID) OTHER_USER_ID, MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID FROM (
            SELECT MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID, RECEIVER_ID, CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          ) t ORDER BY OTHER_USER_ID, SENT_AT DESC
        )
        SELECT CU.OTHER_USER_ID, U.FULL_NAME, P.IMAGE_URL AS PROFILE_PICTURE_URL, 
               LM.MESSAGE_CONTENT AS LAST_MESSAGE, LM.MESSAGE_TYPE AS LAST_MESSAGE_TYPE, LM.SENDER_ID AS LAST_MESSAGE_SENDER_ID, 
               'you' AS swipe_category, 
               COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) AS LAST_MESSAGE_SENT_AT 
        FROM conversation_users CU 
        LEFT JOIN last_messages LM ON LM.OTHER_USER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S1 ON S1.SWIPER_ID = ${user_id} AND S1.RECEIVER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S2 ON S2.SWIPER_ID = CU.OTHER_USER_ID AND S2.RECEIVER_ID = ${user_id} 
        LEFT JOIN BLOCKS B1 ON B1.BLOCKER_ID = ${user_id} AND B1.BLOCKED_ID = CU.OTHER_USER_ID 
        LEFT JOIN BLOCKS B2 ON B2.BLOCKER_ID = CU.OTHER_USER_ID AND B2.BLOCKED_ID = ${user_id} 
        JOIN USERS U ON U.USER_ID = CU.OTHER_USER_ID 
        JOIN PHOTOS P ON P.UPLOADER_ID = CU.OTHER_USER_ID AND P.IS_PRIMARY = TRUE 
        WHERE B1.BLOCKED_ID IS NULL AND B2.BLOCKED_ID IS NULL 
          AND S1.SWIPE_TYPE = 'like' AND (S2.SWIPE_TYPE IS NULL OR S2.SWIPE_TYPE != 'like')
        ORDER BY COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) DESC 
        OFFSET ${offset} LIMIT ${limit}
      `,
    );
  }

  async getConversationsThey(
    user_id: string,
    limit: number,
    offset: number,
  ): Promise<ConversationDto[]> {
    return Array.from(
      await Bun.sql`
        WITH conversation_users AS (
          SELECT CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          UNION SELECT RECEIVER_ID AS OTHER_USER_ID FROM SWIPES WHERE SWIPER_ID = ${user_id}
          UNION SELECT SWIPER_ID AS OTHER_USER_ID FROM SWIPES WHERE RECEIVER_ID = ${user_id}
        ),
        last_messages AS (
          SELECT DISTINCT ON (OTHER_USER_ID) OTHER_USER_ID, MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID FROM (
            SELECT MESSAGE_ID, MESSAGE_CONTENT, MESSAGE_TYPE, SENT_AT, SENDER_ID, RECEIVER_ID, CASE WHEN SENDER_ID = ${user_id} THEN RECEIVER_ID ELSE SENDER_ID END AS OTHER_USER_ID FROM MESSAGES WHERE SENDER_ID = ${user_id} OR RECEIVER_ID = ${user_id}
          ) t ORDER BY OTHER_USER_ID, SENT_AT DESC
        )
        SELECT CU.OTHER_USER_ID, U.FULL_NAME, P.IMAGE_URL AS PROFILE_PICTURE_URL, 
               LM.MESSAGE_CONTENT AS LAST_MESSAGE, LM.MESSAGE_TYPE AS LAST_MESSAGE_TYPE, LM.SENDER_ID AS LAST_MESSAGE_SENDER_ID, 
               'they' AS swipe_category, 
               COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) AS LAST_MESSAGE_SENT_AT 
        FROM conversation_users CU 
        LEFT JOIN last_messages LM ON LM.OTHER_USER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S1 ON S1.SWIPER_ID = ${user_id} AND S1.RECEIVER_ID = CU.OTHER_USER_ID 
        LEFT JOIN SWIPES S2 ON S2.SWIPER_ID = CU.OTHER_USER_ID AND S2.RECEIVER_ID = ${user_id} 
        LEFT JOIN BLOCKS B1 ON B1.BLOCKER_ID = ${user_id} AND B1.BLOCKED_ID = CU.OTHER_USER_ID 
        LEFT JOIN BLOCKS B2 ON B2.BLOCKER_ID = CU.OTHER_USER_ID AND B2.BLOCKED_ID = ${user_id} 
        JOIN USERS U ON U.USER_ID = CU.OTHER_USER_ID 
        JOIN PHOTOS P ON P.UPLOADER_ID = CU.OTHER_USER_ID AND P.IS_PRIMARY = TRUE 
        WHERE B1.BLOCKED_ID IS NULL AND B2.BLOCKED_ID IS NULL 
          AND S2.SWIPE_TYPE = 'like' AND (S1.SWIPE_TYPE IS NULL OR S1.SWIPE_TYPE != 'like')
        ORDER BY COALESCE(LM.SENT_AT, S1.SWIPED_AT, S2.SWIPED_AT) DESC 
        OFFSET ${offset} LIMIT ${limit}
      `,
    );
  }
}
