export class UserDto {
  user_id!: string;
  email!: string;
  password_hash!: string;
  full_name!: string;
  gender!: string;
  sexual_orientation!: string;
  profile_picture_url!: string | null;
  birth_date!: Date;
  bio!: string;
  created_at!: Date;
  pref_genders!: string;
  pref_min_age!: number;
  pref_max_age!: number;
  pref_distance_radius_km!: number;
  is_active!: boolean;
  is_onboarded!: boolean;
  is_verified!: boolean;
  allow_messages_from_strangers!: boolean;
};
